name: lj_speedrun
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  chopper: ^4.0.4
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  get_it: ^7.2.0
  json_serializable: ^6.1.4
  equatable: ^2.0.3
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  chopper_generator: ^4.0.3
  json_annotation: ^4.4.0

flutter:
  uses-material-design: true
